$remotes = @( "Admin@ST-106-01"
    # , "Admin@ST-106-02"
    # , "Admin@ST-106-03"
    # , "Admin@ST-106-04"
    # , "Admin@ST-106-05"
    # , "Admin@ST-106-06"
    # , "Admin@ST-106-07"
    , "Admin@ST-106-08"
    , "Admin@ST-106-09"
    , "Admin@ST-106-10"
    , "Admin@ST-106-11"
    , "Admin@ST-106-12"
    , "Admin@ST-106-13"
    , "Admin@ST-106-14"
    , "Admin@ST-106-15"
    , "Admin@ST-106-16"
    , "Admin@ST-106-17"
    , "Admin@ST-106-18"
    , "Admin@ST-106-19"
    , "Admin@ST-106-20"
    , "Admin@ST-106-21"
    , "Admin@ST-106-22"
)

foreach($remote in $remotes) {
    #scp "$PSScriptRoot\scripts\Set-English.ps1"  "${remote}:C:\Control\Scripts"
    #scp "$PSScriptRoot\scripts\Clear-Apps.ps1"  "${remote}:C:\Control\Scripts"

    #ssh $remote "powershell -File C:\Control\Scripts\Set-English.ps1"
    # ssh $remote "powershell -File C:\Control\Scripts\Clear-Apps.ps1"
    ssh $remote "powershell -File C:\Control\Scripts\Disable-ChangeSettings.ps1"
    ssh $remote "powershell Stop-Computer -Force"

    #ssh $remote "powershell -File C:\Control\Scripts\Apply-Wallpaper.ps1"
    #ssh $remote "powershell -Command Write-Host $remote connected"
    #ssh $remote "powershell -Command Set-ExecutionPolicy -ExecutionPolicy Bypass -Force"
}
