$remotes104 = @( "Admin@ST-104-02"
    # , "Admin@ST-104-02"
    # , "Admin@ST-104-03"
    # , "Admin@ST-104-04"
    # , "Admin@ST-104-05"
    # , "Admin@ST-104-06"
    # , "Admin@ST-104-07"
    # , "Admin@ST-104-08"
    # , "Admin@ST-104-09"
    # , "Admin@ST-104-10"
    # , "Admin@ST-104-11"
    # , "Admin@ST-104-12"
    # , "Admin@ST-104-13"
    # , "Admin@ST-104-14"
    # , "Admin@ST-104-15"
    # , "Admin@ST-104-16"
    # , "Admin@ST-104-17"
    # , "Admin@ST-104-18"
    # , "Admin@ST-104-19"
    # , "Admin@ST-104-20"
    # , "Admin@ST-104-21"
    # , "Admin@ST-104-22"
)

foreach($remote in $remotes104) {    
    #scp "D:\*"  "${remote}:C:\Users\Public"
    ssh $remote powershell New-Item -Path "C:\" -ItemType "directory" -Name "Games"
    scp -r "C:\Users\Abai\Downloads\Baba Is You"  "${remote}:C:\Games"
    #ssh $remote "powershell -File C:\Control\Scripts\Set-English.ps1"

    #ssh $remote "powershell -File C:\Control\Scripts\Disable-ChangeSettings.ps1"
    #ssh $remote "powershell -File C:\Control\Scripts\Clear-Apps.ps1"

    #ssh $remote "powershell Stop-Computer -Force"
    #ssh $remote "powershell -File C:\Control\Scripts\Apply-Wallpaper.ps1"
    #ssh $remote "powershell -Command Set-ExecutionPolicy -ExecutionPolicy Bypass -Force"
}
