$remotes = @( "Admin@ST-106-01"
    , "Admin@ST-106-02"
    , "Admin@ST-106-03"
    , "Admin@ST-106-04"
    , "Admin@ST-106-05"
    , "Admin@ST-106-06"
    , "Admin@ST-106-07"
    , "Admin@ST-106-08"
    , "Admin@ST-106-09"
    , "Admin@ST-106-10"
    , "Admin@ST-106-11"
    , "Admin@ST-106-12"
    , "Admin@ST-106-13"
    , "Admin@ST-106-14"
    , "Admin@ST-106-15"
    , "Admin@ST-106-16"
    , "Admin@ST-106-17"
    , "Admin@ST-106-18"
    , "Admin@ST-106-19"
    , "Admin@ST-106-20"
    , "Admin@ST-106-21"
    , "Admin@ST-106-22"
)

$scripts = "$PSScriptRoot\scripts"
$images = "$PSScriptRoot\images"
$destination = "C:\Control"

foreach($remote in $remotes) {
    ssh $remote "powershell -Command New-Item -Path $destination -ItemType Directory -Force ; New-Item -Path $destination -ItemType Directory -Force"
    scp -r $scripts "${remote}:$destination"
    scp -r $images  "${remote}:$destination"
    ssh $remote "powershell -File C:\Control\Scripts\Confirm-Setup.ps1"
    ssh $remote "powershell -File C:\Control\Scripts\Enable-ChangeSettings.ps1"
    ssh $remote "powershell -File C:\Control\Scripts\Apply-Wallpaper.ps1"
    #ssh $remote "powershell -Command Restart-Computer -Force"
}